app = "nhom4superset"

[build]
  dockerfile = "Dockerfile"

[env]
  FLY_REGION = "sin"

[limits]
  memory = "8Gi"     
  cpu = "8"          

[mounts]
  source = "superset_data"
  destination = "/app/superset_home"

[ip6]
  # Kích hoạt địa chỉ IPv6
  allocated = true

[ip4]
  # Kích hoạt địa chỉ IPv4 tĩnh
  allocated = true